name: Kingdoms
main: com.minederp.kingdoms.KingdomsPlugin
version: "${project.version}"
commands:
    kingdom:
        description: Kingdom commands
        usage: /<command> <arguments...>
    town:
        description: Town commands
        usage: /<command> <arguments...>
    plot:
        description: Plot commands
        usage: /<command> <arguments...>
    tet:
        description: Tetris based commands
        usage: /tet ()
    ctf:
        description: Capture the flag commands
        usage: /ctf (setrectangle|startgame|endgame|join) ((red|blue) (setflag|setspawn))  
    z:
        description: Zombies commands
        usage: /z (SetRectangle|StartGame|EndGame|Join) (SetHuman|SetZombie)  
    zombies:
        description: Zombies commands
        usage: /zombies (SetRectangle|StartGame|EndGame|Join) (SetHuman|SetZombie)  
    m:
        description: Map based commands
        usage: /m (SetId {index})  
    map:
        description: Map based commands
        usage: /map (SetId {index})  
    t:
        description: Town based commands
        usage: /t (ShowWalls(False|True)|SetPolygon)
    p:
        description: Plot based commands
        usage: /p (ShowWalls(False|True)|SetPolygon)
    k:
        description: Kingdom based commands
        usage: /k (Join)
    town:
        description: Town based commands
        usage: /t (ShowWalls(False|True)|SetPolygon)
    c:
        description: Construction based commands
        usage: /t (CreateJob(jobname)|AddChestToJob(jobname)|AddCraneToJob(jobname))
    construction:
        description: Construction based commands
        usage: /t (CreateJob(jobname)|AddChestToJob(jobname)|AddCraneToJob(jobname))
    b:
        description: Bulldozer based commands
        usage: /b ()
    bulldozer:
        description: Bulldozer based commands
        usage: /b ()
    tc:
        description: Tictactoe based commands
        usage: /tc ()
