name: Kingdoms
main: com.minederp.kingdoms.KingdomsPlugin
version: "${project.version}"
commands:
    kingdom:
        description: Kingdom commands
        usage: /<command> <arguments...>
    town:
        description: Town commands
        usage: /<command> <arguments...>